apiVersion: v1
kind: Namespace
metadata:
  name: uptimekuma
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptimekuma
spec:
  selector:
    matchLabels:
      app: uptimekuma
  replicas: 1
  template:
    metadata:
      labels:
        app: uptimekuma
    spec:
      containers:
        - name: uptimekuma
          image: louislam/uptime-kuma
          ports:
            - containerPort: 3001