apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  # settings.yaml: ""
  settings.yaml: |
    background:
      image: https://images.unsplash.com/photo-1637825891028-564f672aa42c
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Repositories:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Networking:
        - My First Service:
            href: http://localhost/
            description: Homepage is awesome

    - Infrastructure:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - Management:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎

    - Monitoring:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""