apiVersion: v1
kind: Namespace
metadata:
  name: semaphore
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-pvc
  namespace: semaphore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata: 
  name: semaphore-secret
  namespace: semaphore
type: Opaque
data:
#use echo -n <base64-encoded-string> |base64 -d to decode
  SEMAPHORE_ADMIN: YWRtaW4=
  SEMAPHORE_ADMIN_PASSWORD: QW5pc2lAMDgwNDIz
  SEMAPHORE_DB_NAME: c2VtYXBob3JlX2Rldg==
  SEMAPHORE_DB_USER: ZGJhZG1pbg==
  SEMAPHORE_DB_PASS: QW5pc2lAMDgwNDIz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: semaphore
  name: semaphore
  namespace: semaphore
spec:
  selector:
    matchLabels:
      app: semaphore
  replicas: 1
  template:
    metadata:
      labels:
        app: semaphore
    spec:
      containers:
        - env:
            - name: SEMAPHORE_ADMIN
              valueFrom:
                secretKeyRef:
                  name: semaphore-secret
                  key: SEMAPHORE_ADMIN
                  optional: false
            - name: SEMAPHORE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: semaphore-secret
                  key: SEMAPHORE_ADMIN_PASSWORD
                  optional: false
            - name: SEMAPHORE_ADMIN_NAME
              value: Razvan
            - name: SEMAPHORE_ADMIN_EMAIL
              value: razvan@cranganu.me
            - name: SEMAPHORE_PORT
              value: ":3000"
            - name: SEMAPHORE_DB_DIALECT
              value: mysql
            - name: SEMAPHORE_DB_HOST
              value: 10.10.4.100
            - name: SEMAPHORE_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: semaphore-secret
                  key: SEMAPHORE_DB_NAME
                  optional: false
            - name: SEMAPHORE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: semaphore-secret
                  key: SEMAPHORE_DB_USER
                  optional: false
            - name: SEMAPHORE_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: semaphore-secret
                  key: SEMAPHORE_DB_PASSWORD
                  optional: false
            - name: SEMAPHORE_PLAYBOOK_PATH
              value: /tmp/sempahore
          name: semaphore
          image: semaphoreui/semaphore:v2.10.43
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /tmp/semaphore
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: semaphore-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: semaphoreui
  namespace: semaphore
spec:
  selector:
    app: semaphore
  ports:
    - protocol: TCP
      name: web
      port: 3000
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: semaphore-certificate
  namespace: semaphore
spec:
  secretName: tls-semaphore-certificate
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - semaphore.dev.k3s.rcrg.me
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: semaphore-ingressroute
  namespace: semaphore
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`semaphore.dev.k3s.rcrg.me`)
    kind: Rule
    services:
    - name: semaphoreui
      port: 3000
  tls:
    secretName: tls-semaphore-certificate